
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::713881819246:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-YFMyS90xrd0y
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::713881819246:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-16T05:46:05Z"
  name: aws-auth
  namespace: kube-system
  # uid: 932917b1-6af4-46e4-be4d-74211890b0cd
